#!/bin/sh
WEBMATICDIR=/usr/local/etc/config/addons/www/webmatic
CONFIG_URL=/addons/webmatic/index.html

case "$1" in

  ""|start|restart|stop)
    exit 0
  ;;

  info)
    VER=$(cat ${WEBMATICDIR}/VERSION)
    echo "Info: <center>"
    echo "Info: <b>WebMatic ${VER}</b><br>"
    echo "Info: <img src='/addons/webmatic/img/misc/webmatic.png'><br>"
    echo "Info: <a href='https://github.com/jens-maus/webmatic'>Weitere Infos</a>"
    echo "Info: </center>"
    echo "Name: WebMatic"
    echo "Version: ${VER}"
    echo "Operations: uninstall"
    echo "Config-Url: ${CONFIG_URL}"
    echo "Update: /addons/webmatic/cgi/update-check.cgi"
  ;;

  uninstall)
    ${WEBMATICDIR}/update_addon webmatic
    rm -rf ${WEBMATICDIR}
  ;;

  *)
    echo "Usage: webmatic {info|uninstall}" >&2
    exit 1
  ;;

esac 

exit 0
