#!/bin/sh

WWWDIR=/mnt/etc/config/addons/www/webmatic
RCDDIR=/mnt/etc/config/rc.d
USERDIR=/mnt/etc/config/addons/www/webmatic_user

mkdir -p /mnt

if [ "$1" == "" ]; then
    echo "CCU1"
	lcdtool "installing WebMatic      "
    mount -t yaffs /dev/mtdblock3 /mnt
elif [ "$1" == "CCU2" ]; then
    echo "CCU2"
    mount -t ubifs ubi1:user /mnt
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
    echo "HM-RASPBERRYMATIC"
    mount /usr/local
    mount --bind /usr/local /mnt
fi

mkdir -p $WWWDIR
chmod 755 $WWWDIR
mkdir -p $RCD_DIR
chmod 755 $RCD_DIR
mkdir -p $USERDIR
chmod 755 $USERDIR

rm -f $WWWDIR/*

cp -R webmatic/* $WWWDIR/
cp VERSION $WWWDIR/
cp -R -n webmatic_user/* $USERDIR/
cp webmatic-dlg $RCDDIR/
chmod +x $RCDDIR/webmatic-dlg

umount /mnt

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
        echo "CCU1"
        lcdtool "Reboot...             "
        lcdtool -a 0x40 -t bin 00
        echo "x" > /dev/watchdog
        reboot
        while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
        echo "CCU2"
        # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
        echo "HM-RASPBERRYMATIC"
        umount /usr/local
        # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
